"use client";

import { useEffect, useState } from "react";
import { createGraphDraft, fetchGraphMail, fetchGraphMailStatus, generateSummary } from "@/lib/api";
import type { GraphEmail, SummaryResponse } from "@/lib/types";

// Used to compose draft content before any report data has loaded.
const EXAMPLE_EMAIL_MD = `# PE AI System — Weekly Summary

**Report Period:** Aug 26, 2026 – Sep 2, 2026

## Key Metrics

| Metric | Value |
|--------|-------|
| Total Queries | 47 |
| Avg Confidence | 84% |
| Active Users | 3 |

## Agent Usage

| Agent | Queries |
|-------|---------|
| Due Diligence | 18 |
| Term Sheet | 12 |
| Compliance | 8 |

_This report was auto-generated by the PE AI Engineering Platform._`;

export default function SummaryPage() {
  const [data, setData] = useState<SummaryResponse | null>(null);
  const [period, setPeriod] = useState<"week" | "month">("week");

  const [mailStatus, setMailStatus] = useState<{
    configured: boolean;
    demo?: boolean;
    reason?: string;
    mailbox?: string;
  } | null>(null);
  const [mailEmails, setMailEmails] = useState<GraphEmail[]>([]);
  const [mailLoading, setMailLoading] = useState(false);
  const [mailError, setMailError] = useState<string | null>(null);
  const [openEmail, setOpenEmail] = useState<string | null>(null);
  const [toValue, setToValue] = useState("");
  const [draftBusy, setDraftBusy] = useState(false);
  const [draftMsg, setDraftMsg] = useState<{ ok: boolean; text: string } | null>(null);

  const mailActive = !!mailStatus && (!!mailStatus.configured || !!mailStatus.demo);
  const periodLabel = data?.period_label ?? "Last 7 Days";

  async function load(p: "week" | "month") {
    setPeriod(p);
    try {
      const r = await generateSummary(p);
      setData(r);
    } catch {
      setData(null);
    }
  }

  useEffect(() => {
    load("week");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  useEffect(() => {
    let alive = true;
    fetchGraphMailStatus()
      .then((st) => {
        if (!alive) return;
        setMailStatus(st);
        if (!st.configured && !st.demo) return;
        setMailLoading(true);
        fetchGraphMail(30)
          .then((r) => alive && setMailEmails(r.emails))
          .catch(() => alive && setMailError("Couldn't load the mailbox."))
          .finally(() => alive && setMailLoading(false));
      })
      .catch(() =>
        alive && setMailStatus({ configured: false, reason: "Graph mail unavailable." }),
      );
    return () => {
      alive = false;
    };
  }, []);

  async function handleCreateDraft() {
    const md = data?.email_markdown ?? EXAMPLE_EMAIL_MD;
    setDraftBusy(true);
    setDraftMsg(null);
    try {
      const to = toValue
        .split(",")
        .map((x) => x.trim())
        .filter(Boolean);
      const res = await createGraphDraft(
        `${periodLabel} Platform Report — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`,
        md,
        to,
      );
      setDraftMsg({
        ok: true,
        text: `Draft created${mailStatus?.demo ? " (demo — saved locally)" : res.draft_link ? " — open it in Outlook to review" : ""}.`,
      });
    } catch (e) {
      setDraftMsg({
        ok: false,
        text: e instanceof Error ? e.message : "Couldn't create the draft.",
      });
    } finally {
      setDraftBusy(false);
    }
  }

  return (
    <section className="section">
      <div className="container">
        <div className="section-intro">
          <span className="section-eyebrow">Email</span>
          <h1>Outlook mailbox.</h1>
          <p style={{ color: "var(--color-muted)", fontSize: "0.92rem", maxWidth: "38rem", lineHeight: 1.6 }}>
            Read your inbox and save platform reports as drafts via the
            Microsoft Graph API — nothing is sent until you send it.
          </p>
        </div>

        {/* Period toggle (controls which report a draft is based on) */}
        <div style={{ display: "flex", gap: "0.5rem", margin: "1rem 0 0.25rem" }}>
          <button
            type="button"
            onClick={() => load("week")}
            className={`button button--small ${period === "week" ? "button--solid" : "button--ghost"}`}
          >
            Last 7 Days
          </button>
          <button
            type="button"
            onClick={() => load("month")}
            className={`button button--small ${period === "month" ? "button--solid" : "button--ghost"}`}
          >
            Last 30 Days
          </button>
        </div>
        <p style={{ margin: "0.25rem 0 1.25rem", fontSize: "0.76rem", color: "var(--color-muted)" }}>
          Drafts are composed from the {period === "week" ? "weekly" : "monthly"} report.
        </p>

        {/* Mailbox + draft */}
        <div
          className="grid gap-6"
          style={{
            gridTemplateColumns: "repeat(auto-fit, minmax(20rem, 1fr))",
            alignItems: "start",
          }}
        >
          <div className="panel-card" style={{ padding: "1rem 1.1rem" }}>
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "baseline",
                marginBottom: "0.5rem",
              }}
            >
              <span
                style={{
                  fontSize: "0.78rem",
                  fontWeight: 600,
                  textTransform: "uppercase",
                  letterSpacing: "0.06em",
                  color: "var(--color-muted)",
                }}
              >
                Recent mail
              </span>
              <span style={{ fontSize: "0.7rem", color: "var(--color-muted)" }}>
                {mailStatus?.mailbox}
                {mailStatus?.demo ? " · demo" : ""}
              </span>
            </div>

            {mailLoading && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)" }}>
                Loading mailbox...
              </p>
            )}
            {!mailLoading && mailError && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-error)" }}>
                {mailError}
              </p>
            )}
            {!mailLoading && mailActive && mailEmails.length === 0 && !mailError && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)" }}>
                No messages in the mailbox yet.
              </p>
            )}
            {mailActive && mailEmails.length > 0 && (
              <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "grid", gap: "0.15rem" }}>
                {mailEmails.map((email) => (
                  <li key={email.id} style={{ borderBottom: "1px solid var(--color-line)" }}>
                    <button
                      type="button"
                      onClick={() => setOpenEmail(openEmail === email.id ? null : email.id)}
                      style={{
                        width: "100%",
                        background: "none",
                        border: "none",
                        textAlign: "left",
                        cursor: "pointer",
                        padding: "0.6rem 0.15rem",
                        display: "grid",
                        gap: "0.15rem",
                      }}
                    >
                      <span
                        style={{
                          fontSize: "0.86rem",
                          fontWeight: 600,
                          color: "var(--color-ink)",
                          overflowWrap: "anywhere",
                        }}
                      >
                        {email.subject || "(no subject)"}
                      </span>
                      <span style={{ fontSize: "0.72rem", color: "var(--color-muted)" }}>
                        {email.from}
                        {email.received_at
                          ? " · " +
                            new Date(email.received_at).toLocaleString("en-US", {
                              month: "short",
                              day: "numeric",
                              hour: "2-digit",
                              minute: "2-digit",
                            })
                          : ""}
                      </span>
                    </button>
                    {openEmail === email.id && (
                      <div
                        style={{
                          padding: "0 0.4rem 0.7rem",
                          fontSize: "0.82rem",
                          color: "var(--color-muted)",
                          lineHeight: 1.5,
                        }}
                      >
                        {email.body_preview || "No preview."}
                        {email.web_link && (
                          <div style={{ marginTop: "0.4rem" }}>
                            <a
                              href={email.web_link}
                              target="_blank"
                              rel="noopener noreferrer"
                              style={{ fontSize: "0.78rem", color: "var(--color-accent)" }}
                            >
                              Open in Outlook ↗
                            </a>
                          </div>
                        )}
                      </div>
                    )}
                  </li>
                ))}
              </ul>
            )}
            {!mailLoading && mailStatus && !mailActive && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
                {mailStatus.reason || "Mailbox access is not configured."}
              </p>
            )}
          </div>

          <div className="panel-card" style={{ padding: "1rem 1.1rem" }}>
            <div className="section-intro" style={{ marginBottom: "0.5rem" }}>
              <span className="section-eyebrow">Draft</span>
              <h2 style={{ fontSize: "1.1rem", margin: 0 }}>Save report as draft</h2>
            </div>
            <p style={{ margin: "0 0 0.75rem", fontSize: "0.82rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
              Creates a draft of the {period === "week" ? "weekly" : "monthly"} report in the
              connected mailbox's Drafts folder. Nothing is sent until you send it.
            </p>
            <input
              className="input"
              style={{ width: "100%", marginBottom: "0.6rem" }}
              placeholder="To (optional, comma separated)"
              value={toValue}
              onChange={(e) => setToValue(e.target.value)}
              disabled={!mailActive || draftBusy}
            />
            <button
              type="button"
              className="button"
              style={{ width: "100%" }}
              onClick={handleCreateDraft}
              disabled={!mailActive || draftBusy}
            >
              {draftBusy ? "Creating draft..." : "Create draft"}
            </button>
            {draftMsg && (
              <p
                style={{
                  margin: "0.7rem 0 0",
                  fontSize: "0.8rem",
                  lineHeight: 1.45,
                  color: draftMsg.ok ? "var(--color-accent)" : "var(--color-error)",
                }}
              >
                {draftMsg.text}
              </p>
            )}
            {mailStatus?.demo && (
              <p style={{ margin: "0.7rem 0 0", fontSize: "0.76rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
                Running on demo mail — drafts are saved locally
                (data/graph_drafts.db). Configure Graph in .env for your real
                Outlook mailbox.
              </p>
            )}
          </div>
        </div>
      </div>
    </section>
  );
}
