"use client";
import { useEffect, useState } from "react";
import { generateSummary } from "@/lib/api";
import type { SummaryResponse } from "@/lib/types";
import StatCard from "@/components/StatCard";
import EmailPreview from "@/components/EmailPreview";
import { formatPercent, formatCount } from "@/lib/utils";

// Shown in the email preview when a period has no activity yet, so the report
// format is still demonstrable (example content only).
const EXAMPLE_EMAIL_MD = `# PE AI System — Weekly Summary

**Report Period:** Aug 26, 2026 – Sep 2, 2026
**Generated:** Sep 3, 2026

---

## Key Metrics

| Metric | Value |
|--------|-------|
| Total Queries | 47 |
| Avg Confidence | 84% |
| Active Users | 3 |
| Agent Types Used | 5 |

## Agent Usage

| Agent | Queries | Share |
|-------|---------|-------|
| Due Diligence | 18 | 38% |
| Term Sheet | 12 | 26% |
| Compliance | 8 | 17% |
| LP Report | 5 | 11% |
| Cross-Document | 4 | 9% |

## User Activity

| User | Queries |
|------|---------|
| admin | 29 |
| analyst | 12 |
| partner | 6 |

## Recent Queries

1. **Summarize the key risks in the Enosis term sheet**
   — _term_sheet_ | 91% confidence | 2026-09-01 14:32
2. **Compare liquidation preferences across all three decks**
   — _cross_doc_ | 87% confidence | 2026-09-01 11:15
3. **What are the anti-dilution provisions in the Dr. Yip proposal?**
   — _term_sheet_ | 83% confidence | 2026-08-31 16:48

---

_This report was auto-generated by the PE AI Engineering Platform._
_Audit trail integrity: tamper-evident hash chain (SHA-256)._`;

export default function SummaryPage() {
  const [data, setData] = useState<SummaryResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [period, setPeriod] = useState<"week" | "month">("week");

  async function load(p: "week" | "month") {
    setPeriod(p);
    setLoading(true);
    setError(null);
    try {
      const r = await generateSummary(p);
      setData(r);
    } catch {
      setError("Couldn't generate the report. Is the backend running?");
      setData(null);
    } finally {
      setLoading(false);
    }
  }

  // Load the default period on first visit so the page is never empty.
  useEffect(() => {
    load("week");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <section className="section">
      <div className="container">
        <div className="section-intro">
          <span className="section-eyebrow">Summary</span>
          <h1 style={{ fontSize: "clamp(1.4rem, 3.8vw, 2rem)", fontFamily: "var(--font-display)", fontWeight: 400, lineHeight: 1.15, letterSpacing: "-0.01em", marginBottom: "1rem" }}>
            Email reports.
          </h1>
          <p>
            Generate email-ready reports from the audit trail. Covers query
            volume, agent usage, and confidence scores.
          </p>
        </div>

        {/* Period Selector */}
        <div className="flex gap-3" style={{ marginBottom: "2.5rem" }}>
          <button
            onClick={() => load("week")}
            className={`button button--small ${period === "week" && !loading ? "button--solid" : "button--ghost"}`}
          >
            Last 7 Days
          </button>
          <button
            onClick={() => load("month")}
            className={`button button--small ${period === "month" && !loading ? "button--solid" : "button--ghost"}`}
          >
            Last 30 Days
          </button>
        </div>

        {/* Loading */}
        {loading && (
          <p
            style={{
              color: "var(--color-muted)",
              textAlign: "center",
              padding: "3rem 0",
              fontSize: "0.88rem",
            }}
          >
            Generating summary...
          </p>
        )}

        {/* Error */}
        {error && !loading && (
          <p
            style={{
              color: "var(--color-muted)",
              textAlign: "center",
              padding: "3rem 0",
              fontSize: "0.88rem",
            }}
          >
            {error}
          </p>
        )}

        {/* Data */}
        {data && !loading && data.total_queries === 0 && (
          <div className="space-y-8">
            <div
              className="panel-card"
              style={{
                textAlign: "center",
                padding: "2rem 1.5rem",
                color: "var(--color-muted)",
                fontSize: "0.9rem",
              }}
            >
              No activity in this period yet. Ask the agents a few questions
              and this report will reflect them.
            </div>
            <div>
              <div className="section-intro">
                <span className="section-eyebrow">Preview</span>
                <h2>Email preview.</h2>
              </div>
              <EmailPreview text={EXAMPLE_EMAIL_MD} caption="Example email format" />
            </div>
          </div>
        )}
        {data && !loading && data.total_queries > 0 && (
          <div className="space-y-8">
            {/* Metric Cards */}
            <div
              className="grid gap-4"
              style={{
                gridTemplateColumns: "repeat(auto-fit, minmax(12rem, 1fr))",
              }}
            >
              <StatCard value={formatCount(data.total_queries)} label="Total Queries" />
              <StatCard
                value={`${formatPercent((data.avg_confidence ?? 0) * 100)}%`}
                label="Avg Confidence"
              />
              <StatCard value={formatCount(data.user_activity.length)} label="Active Users" />
              <StatCard
                value={formatCount(data.agent_breakdown.length)}
                label="Agent Types"
              />
            </div>

            {/* Agent Usage */}
            {data.agent_breakdown.length > 0 && (
              <div>
                <div className="section-intro">
                  <span className="section-eyebrow">Usage</span>
                  <h2>Agent breakdown.</h2>
                </div>
                <div className="panel-card">
                  {data.agent_breakdown.map((a) => (
                    <div
                      key={a.agent}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "1rem",
                        padding: "0.75rem 0",
                        borderBottom: "1px solid var(--color-line)",
                        fontSize: "0.88rem",
                      }}
                    >
                      <span style={{ flex: 1, fontWeight: 500 }}>{a.agent}</span>
                      <span style={{ color: "var(--color-muted)" }}>
                        {a.count} queries
                      </span>
                      <span
                        style={{
                          minWidth: "3rem",
                          textAlign: "right",
                          flexShrink: 0,
                          fontVariantNumeric: "tabular-nums",
                          color: "var(--color-muted)",
                        }}
                      >
                        {a.pct}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Recent Queries */}
            {data.top_queries.length > 0 && (
              <div>
                <div className="section-intro">
                  <span className="section-eyebrow">Queries</span>
                  <h2>Recent queries.</h2>
                </div>
                <div className="panel-card">
                  {data.top_queries.map((q, i) => (
                    <div
                      key={i}
                      style={{
                        padding: "0.75rem 0",
                        borderBottom: "1px solid var(--color-line)",
                      }}
                    >
                      <div
                        style={{
                          display: "flex",
                          alignItems: "flex-start",
                          justifyContent: "space-between",
                          gap: "0.75rem",
                        }}
                      >
                        <span style={{ fontSize: "0.88rem", fontWeight: 500, flex: 1 }}>
                          {i + 1}. {q.query}
                        </span>
                        <span
                          style={{
                            fontSize: "0.74rem",
                            color: "var(--color-muted)",
                            flexShrink: 0,
                            marginTop: "0.15rem",
                          }}
                        >
                          {q.agent}
                        </span>
                      </div>
                      <div
                        style={{
                          fontSize: "0.78rem",
                          color: "var(--color-muted)",
                          marginTop: "0.25rem",
                        }}
                      >
                        {q.confidence
                          ? `${Math.round(q.confidence * 100)}% confidence`
                          : ""}
                        {" -- "}
                        {q.timestamp.slice(0, 16).replace("T", " ")}
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Email Preview */}
            <div>
              <div className="section-intro">
                <span className="section-eyebrow">Preview</span>
                <h2>Email preview.</h2>
              </div>
              <div className="panel-card">
                <EmailPreview
                  text={data.email_markdown}
                  caption={
                    data.total_queries === 0
                      ? "Example — no activity recorded in this period yet"
                      : undefined
                  }
                />
              </div>
            </div>
          </div>
        )}
      </div>
    </section>
  );
}
