"use client";
import { useEffect, useState } from "react";
import { generateSummary } from "@/lib/api";
import type { SummaryResponse } from "@/lib/types";
import StatCard from "@/components/StatCard";
import EmailPreview from "@/components/EmailPreview";
import {
  createGraphDraft,
  fetchGraphMail,
  fetchGraphMailStatus,
} from "@/lib/api";
import type { GraphEmail } from "@/lib/types";
import { formatPercent, formatCount } from "@/lib/utils";

// Shown in the email preview when a period has no activity yet, so the report
// format is still demonstrable (example content only).
const EXAMPLE_EMAIL_MD = `# PE AI System — Weekly Summary

**Report Period:** Aug 26, 2026 – Sep 2, 2026
**Generated:** Sep 3, 2026

---

## Key Metrics

| Metric | Value |
|--------|-------|
| Total Queries | 47 |
| Avg Confidence | 84% |
| Active Users | 3 |
| Agent Types Used | 5 |

## Agent Usage

| Agent | Queries | Share |
|-------|---------|-------|
| Due Diligence | 18 | 38% |
| Term Sheet | 12 | 26% |
| Compliance | 8 | 17% |
| LP Report | 5 | 11% |
| Cross-Document | 4 | 9% |

## User Activity

| User | Queries |
|------|---------|
| admin | 29 |
| analyst | 12 |
| partner | 6 |

## Recent Queries

1. **Summarize the key risks in the Enosis term sheet**
   — _term_sheet_ | 91% confidence | 2026-09-01 14:32
2. **Compare liquidation preferences across all three decks**
   — _cross_doc_ | 87% confidence | 2026-09-01 11:15
3. **What are the anti-dilution provisions in the Dr. Yip proposal?**
   — _term_sheet_ | 83% confidence | 2026-08-31 16:48

---

_This report was auto-generated by the PE AI Engineering Platform._
_Audit trail integrity: tamper-evident hash chain (SHA-256)._`;

export default function SummaryPage() {
  const [data, setData] = useState<SummaryResponse | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [period, setPeriod] = useState<"week" | "month">("week");

  async function load(p: "week" | "month") {
    setPeriod(p);
    setLoading(true);
    setError(null);
    try {
      const r = await generateSummary(p);
      setData(r);
    } catch {
      setError("Couldn't generate the report. Is the backend running?");
      setData(null);
    } finally {
      setLoading(false);
    }
  }

  // Load the default period on first visit so the page is never empty.
  useEffect(() => {
    load("week");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // --- Microsoft Graph mailbox ---
  const [mailStatus, setMailStatus] = useState<{ configured: boolean; reason?: string; mailbox?: string } | null>(null);
  const [mailEmails, setMailEmails] = useState<GraphEmail[]>([]);
  const [mailLoading, setMailLoading] = useState(false);
  const [mailError, setMailError] = useState<string | null>(null);
  const [openEmail, setOpenEmail] = useState<string | null>(null);
  const [toValue, setToValue] = useState("");
  const [draftBusy, setDraftBusy] = useState(false);
  const [draftMsg, setDraftMsg] = useState<{ ok: boolean; text: string } | null>(null);

  useEffect(() => {
    let alive = true;
    fetchGraphMailStatus()
      .then((st) => {
        if (!alive) return;
        setMailStatus(st);
        if (!st.configured) return;
        setMailLoading(true);
        fetchGraphMail(30)
          .then((r) => alive && setMailEmails(r.emails))
          .catch(() => alive && setMailError("Couldn't load the mailbox."))
          .finally(() => alive && setMailLoading(false));
      })
      .catch(() => alive && setMailStatus({ configured: false, reason: "Graph mail unavailable." }));
    return () => {
      alive = false;
    };
  }, []);

  async function handleCreateDraft() {
    const md = data?.email_markdown ?? EXAMPLE_EMAIL_MD;
    setDraftBusy(true);
    setDraftMsg(null);
    try {
      const to = toValue
        .split(",")
        .map((x) => x.trim())
        .filter(Boolean);
      const res = await createGraphDraft(
        `${data?.period_label ?? "Weekly"} Platform Report — ${new Date().toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`,
        md,
        to,
      );
      setDraftMsg({
        ok: true,
        text: `Draft created${res.draft_link ? " — open it in Outlook to review" : ""}.`,
      });
    } catch (e) {
      setDraftMsg({
        ok: false,
        text: e instanceof Error ? e.message : "Couldn't create the draft.",
      });
    } finally {
      setDraftBusy(false);
    }
  }

  return (
    <section className="section">
      <div className="container">
        <div className="section-intro">
          <span className="section-eyebrow">Summary</span>
          <h1 style={{ fontSize: "clamp(1.4rem, 3.8vw, 2rem)", fontFamily: "var(--font-display)", fontWeight: 400, lineHeight: 1.15, letterSpacing: "-0.01em", marginBottom: "1rem" }}>
            Email reports.
          </h1>
          <p>
            Generate email-ready reports from the audit trail. Covers query
            volume, agent usage, and confidence scores.
          </p>
        </div>

        {/* Period Selector */}
        <div className="flex gap-3" style={{ marginBottom: "2.5rem" }}>
          <button
            onClick={() => load("week")}
            className={`button button--small ${period === "week" && !loading ? "button--solid" : "button--ghost"}`}
          >
            Last 7 Days
          </button>
          <button
            onClick={() => load("month")}
            className={`button button--small ${period === "month" && !loading ? "button--solid" : "button--ghost"}`}
          >
            Last 30 Days
          </button>
        </div>

        {/* Loading */}
        {loading && (
          <p
            style={{
              color: "var(--color-muted)",
              textAlign: "center",
              padding: "3rem 0",
              fontSize: "0.88rem",
            }}
          >
            Generating summary...
          </p>
        )}

        {/* Error */}
        {error && !loading && (
          <p
            style={{
              color: "var(--color-muted)",
              textAlign: "center",
              padding: "3rem 0",
              fontSize: "0.88rem",
            }}
          >
            {error}
          </p>
        )}

        {/* Data */}
        {data && !loading && data.total_queries === 0 && (
          <div className="space-y-8">
            <div
              className="panel-card"
              style={{
                textAlign: "center",
                padding: "2rem 1.5rem",
                color: "var(--color-muted)",
                fontSize: "0.9rem",
              }}
            >
              No activity in this period yet. Ask the agents a few questions
              and this report will reflect them.
            </div>
            <div>
              <div className="section-intro">
                <span className="section-eyebrow">Preview</span>
                <h2>Email preview.</h2>
              </div>
              <EmailPreview text={EXAMPLE_EMAIL_MD} caption="Example email format" />
            </div>
          </div>
        )}
        {data && !loading && data.total_queries > 0 && (
          <div className="space-y-8">
            {/* Metric Cards */}
            <div
              className="grid gap-4"
              style={{
                gridTemplateColumns: "repeat(auto-fit, minmax(12rem, 1fr))",
              }}
            >
              <StatCard value={formatCount(data.total_queries)} label="Total Queries" />
              <StatCard
                value={`${formatPercent((data.avg_confidence ?? 0) * 100)}%`}
                label="Avg Confidence"
              />
              <StatCard value={formatCount(data.user_activity.length)} label="Active Users" />
              <StatCard
                value={formatCount(data.agent_breakdown.length)}
                label="Agent Types"
              />
            </div>

            {/* Agent Usage */}
            {data.agent_breakdown.length > 0 && (
              <div>
                <div className="section-intro">
                  <span className="section-eyebrow">Usage</span>
                  <h2>Agent breakdown.</h2>
                </div>
                <div className="panel-card">
                  {data.agent_breakdown.map((a) => (
                    <div
                      key={a.agent}
                      style={{
                        display: "flex",
                        alignItems: "center",
                        gap: "1rem",
                        padding: "0.75rem 0",
                        borderBottom: "1px solid var(--color-line)",
                        fontSize: "0.88rem",
                      }}
                    >
                      <span style={{ flex: 1, fontWeight: 500 }}>{a.agent}</span>
                      <span style={{ color: "var(--color-muted)" }}>
                        {a.count} queries
                      </span>
                      <span
                        style={{
                          minWidth: "3rem",
                          textAlign: "right",
                          flexShrink: 0,
                          fontVariantNumeric: "tabular-nums",
                          color: "var(--color-muted)",
                        }}
                      >
                        {a.pct}%
                      </span>
                    </div>
                  ))}
                </div>
              </div>
            )}

            {/* Email Preview */}
            <div>
              <div className="section-intro">
                <span className="section-eyebrow">Preview</span>
                <h2>Email preview.</h2>
              </div>
              <div className="panel-card">
                <EmailPreview
                  text={data.email_markdown}
                  caption={
                    data.total_queries === 0
                      ? "Example — no activity recorded in this period yet"
                      : undefined
                  }
                />
              </div>
            </div>
          </div>
        )}
      {/* Microsoft Graph mailbox */}
      <div className="space-y-6" style={{ marginTop: "1.25rem" }}>
        <div className="section-intro">
          <span className="section-eyebrow">Mailbox</span>
          <h2>Outlook inbox.</h2>
        </div>

        <div className="grid gap-6" style={{ gridTemplateColumns: "repeat(auto-fit, minmax(20rem, 1fr))", alignItems: "start" }}>
          <div className="panel-card" style={{ padding: "1rem 1.1rem" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "baseline", marginBottom: "0.5rem" }}>
              <span style={{ fontSize: "0.78rem", fontWeight: 600, textTransform: "uppercase", letterSpacing: "0.06em", color: "var(--color-muted)" }}>
                Recent mail
              </span>
              {mailStatus?.mailbox && (
                <span style={{ fontSize: "0.7rem", color: "var(--color-muted)" }}>{mailStatus.mailbox}</span>
              )}
            </div>
            {mailLoading && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)" }}>Loading mailbox...</p>
            )}
            {!mailLoading && mailError && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-error)" }}>{mailError}</p>
            )}
            {!mailLoading && mailStatus && !mailStatus.configured && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
                {mailStatus.reason || "Mailbox access is not configured."}
              </p>
            )}
            {!mailLoading && mailStatus?.configured && mailEmails.length === 0 && !mailError && (
              <p style={{ margin: 0, fontSize: "0.85rem", color: "var(--color-muted)" }}>
                No messages in the mailbox yet.
              </p>
            )}
            {mailStatus?.configured && mailEmails.length > 0 && (
              <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "grid", gap: "0.15rem" }}>
                {mailEmails.map((email) => (
                  <li key={email.id} style={{ borderBottom: "1px solid var(--color-line)" }}>
                    <button
                      type="button"
                      onClick={() => setOpenEmail(openEmail === email.id ? null : email.id)}
                      style={{
                        width: "100%",
                        background: "none",
                        border: "none",
                        textAlign: "left",
                        cursor: "pointer",
                        padding: "0.6rem 0.15rem",
                        display: "grid",
                        gap: "0.15rem",
                      }}
                    >
                      <span style={{ fontSize: "0.86rem", fontWeight: 600, color: "var(--color-ink)", overflowWrap: "anywhere" }}>
                        {email.subject || "(no subject)"}
                      </span>
                      <span style={{ fontSize: "0.72rem", color: "var(--color-muted)" }}>
                        {email.from}
                        {email.received_at ? " · " + new Date(email.received_at).toLocaleString("en-US", { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" }) : ""}
                      </span>
                    </button>
                    {openEmail === email.id && (
                      <div style={{ padding: "0 0.4rem 0.7rem", fontSize: "0.82rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
                        {email.body_preview || "No preview."}
                        {email.web_link && (
                          <div style={{ marginTop: "0.4rem" }}>
                            <a href={email.web_link} target="_blank" rel="noopener noreferrer" style={{ fontSize: "0.78rem", color: "var(--color-accent)" }}>
                              Open in Outlook ↗
                            </a>
                          </div>
                        )}
                      </div>
                    )}
                  </li>
                ))}
              </ul>
            )}
          </div>

          <div className="panel-card" style={{ padding: "1rem 1.1rem" }}>
            <div className="section-intro" style={{ marginBottom: "0.5rem" }}>
              <span className="section-eyebrow">Draft</span>
              <h2 style={{ fontSize: "1.1rem", margin: 0 }}>Send report as draft</h2>
            </div>
            <p style={{ margin: "0 0 0.75rem", fontSize: "0.82rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
              Creates a draft of the current {data?.period_label?.toLowerCase() ?? "weekly"} report in the
              connected mailbox's Drafts folder. Nothing is sent until you send it.
            </p>
            <input
              className="input"
              style={{ width: "100%", marginBottom: "0.6rem" }}
              placeholder="To (optional, comma separated)"
              value={toValue}
              onChange={(e) => setToValue(e.target.value)}
              disabled={!mailStatus?.configured || draftBusy}
            />
            <button
              type="button"
              className="button"
              style={{ width: "100%" }}
              onClick={handleCreateDraft}
              disabled={!mailStatus?.configured || draftBusy}
            >
              {draftBusy ? "Creating draft..." : "Create draft"}
            </button>
            {draftMsg && (
              <p style={{ margin: "0.7rem 0 0", fontSize: "0.8rem", lineHeight: 1.45, color: draftMsg.ok ? "var(--color-accent)" : "var(--color-error)" }}>
                {draftMsg.text}
              </p>
            )}
            {!mailStatus?.configured && (
              <p style={{ margin: "0.7rem 0 0", fontSize: "0.76rem", color: "var(--color-muted)", lineHeight: 1.5 }}>
                Configure GRAPH_TENANT_ID / GRAPH_CLIENT_ID / GRAPH_CLIENT_SECRET (Mail.Read +
                Mail.ReadWrite) in .env to enable drafts.
              </p>
            )}
          </div>
        </div>
      </div>
      </div>
    </section>
  );
}
